command: robot -A C:\Users\xuf\AppData\Local\Temp\RIDEq4is8wq_.d\argfile.txt --listener D:\Workspace\GX1\G1XAutomation\venv\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:5164:False D:\Workspace\GX1\G1XAutomation\Demo_Auto_Test\TestProtocols\TEST_DEMO.txt

TestRunnerAgent: Running under CPython 3.8.0


==========
TEST DEMO 
==========

TE... | FAIL |
No keyword with name 'this is the test demo, started' found.
----------

TE... | PASS |
----------

TE... | FAIL |
Resolving variable '${command_list[0].data.ar_measured_channels[0].u16_TempRef}' failed: IndexError: list index out of range
----------

TE... | PASS |
----------

TE... | PASS |
----------

TE... | FAIL |
5 tests, 3 passed, 2 failed
==========
Debug:   D:\Workspace\GX1\G1XAutomation\Demo_Auto_Test\TestReports\TEST_ROUND_1\TEST DEMO-Message-20230425-170622.log
Output:  D:\Workspace\GX1\G1XAutomation\Demo_Auto_Test\TestReports\TEST_ROUND_1\TEST DEMO-Output-20230425-170622.xml

Log:     D:\Workspace\GX1\G1XAutomation\Demo_Auto_Test\TestReports\TEST_ROUND_1\TEST DEMO-Log-20230425-170622.html
Report:  D:\Workspace\GX1\G1XAutomation\Demo_Auto_Test\TestReports\TEST_ROUND_1\TEST DEMO-Report-20230425-170622.html



Test finished 20230425 17:06:46
